<p><a href="http://cats.cse.ucla.edu/" class="main-site">CATS Main Site</a></p>

<h1><img src="images/logo.png" alt="CATS" /></h1>

<!-- Beginning of compulsory code below -->

<ul class="dropdown dropdown-horizontal">
	
	<li><a href="./">About</a></li>
	<li><a href="./" class="dir">In-house Games</a>
		<ul>
			<li><a href="./">Game1</a></li>
			<li><a href="./">Game2</a></li>
			<li><a href="./">Game3</a></li>
			<li><a href="./">Game4</a></li>
		</ul>
	</li>
	<li><a href="./" class="dir">Technologies</a>
		<ul>
			<li><a href="./">Partner1</a></li>
			<li><a href="./">Partner2</a></li>
			<li><a href="./">Partner3</a></li>
		</ul>
	</li>
	<li><a href="./" class="dir">Other Games</a>
		<ul>
			<li><a href="./">Game1</a></li>
			<li><a href="./">Game2</a></li>
			<li><a href="./">Game3</a></li>
		</ul>
	</li>
	<li><a href="./">Register</a></li>
</ul>

<!-- / END -->
